# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Juliano Marcon
description: > 
  Procurando por um site que fala de Soluções de Software, Tecnologia e liderança? Talves os posts ajudem, mas
  se precisar de apoio, entre em contato por uma das redes sociais! ;-)
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.julianomarcon.com.br" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
about-author: I am a web developer focusing on front-end development. Always hungry to keep learning. # add description
social-twitter: julianomarcon # add your Twitter handle
social-facebook: jmarcon.net # add your Facebook handle
social-github: jmarcon # add your Github handle
social-linkedin: julianomarcon # add your Linkedin handle
social-email: # add your Email address

# Author resume

author:
  name: Juliano Marcon
  img: profile2.jpg
  title: .NET Architect
  address: São Paulo, Brasil
  email: juliano.marcon@outloook.com
  link: https://www.julianomarcon.com.br
  weibo:
  github: jmarcon
  linkedin: julianomarcon
  twitter: julianomarcon
  gavatar: /assets/img/profile2.jpg
  stackoverflow: 6416366

# Disqus
discus-identifier: julianomarcon # add your discus identifier

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

  # Build settings
markdown: kramdown
permalink: /posts/:year/:month/:title/
paginate: 5
paginate_path: "/posts/page/:num"


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - azure-pipelines.yml
  - run.sh
  - update_reveal.sh
  - README.md
  - AppIdeas.md
